title: Super Chengzi
name: superchengzi's Blog
email: lou.cai@icloud.com
author: Super Chengzi
author_nickname: Super Chengzi
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://superchengzi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  superchengzi


repo:
  repository_url: https://github.com/superchengzi/superchengzi.github.io
  branch: master

permalink: '/blog/:slug/'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge

default_og_image: "/favicon.ico"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
